baseURL = "https://www.pollen-robotics.com/"
languageCode = "en-us"
title = "Reachy by Pollen Robotics, an open source programmable humanoid robot"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
googleAnalytics = "UA-164958440-1"

theme = "pollen042020"
relativeURLs = true

[params]
description = "Pollen Robotics is a startup building open source interactive robots based on artificial intelligence. Join the community and find out more about Reachy"
brand = "Pollen Robotics"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
